
export const buildings = [
  'Automatic Feeder',
  'Feeding Station',
  'NelVari Barn',
  'Bee Box',
  'Barn',
  'NelVari Butterfly Garden',
  'Chicken Coop',
  'Crafting Workshop',
  'Greenhouse (Fall)',
  'Greenhouse (Spring)',
  'Greenhouse (Summer)',
  'Greenhouse (Winter)',
  'NelVari Workshop',
  'House',
  'Basic Shed',
  'Silo',
  'Withergate Workshop',
  'Chest'
]

export const craftingTables = [
  'Advanced Furniture Table',
  'Alchemy Table',
  'Baker\'s Station',
  'Basic Furniture Table',
  'Composter',
  'Construction Table',
  'Elven Crafting Table',
  // 'Elven Furniture Table',
  'Elven Juicer',
  'Elven Loom',
  'Elven Seed Maker',
  'Farmer\'s Table',
  'Fish Grill',
  'Glorite Mining Machine',
  'Ice Cream Cart',
  'Industrial Cooking Stove',
  'Jam Maker',
  'Jeweler\'s Desk',
  'Juicer',
  'Seltzer Keg',
  'Mana Anvil',
  'Mana Composter',
  'Mana Infuser Table',
  'Mana Siphoner',
  'Monster Anvil',
  'Monster Composter',
  'Monster Crafting Table',
  'Monster Furniture Table',
  'Monster Juicer',
  'Monster Loom',
  'Monster Seed Maker',
  'Monster Sushi Table',
  'Anvil',
  'Cooking Pot',
  'Crafting Table',
  'Furnace',
  'Loom',
  'Oven',
  'Painter\'s Easel',
  'Recycling Machine',
  'Seed Maker',
  'Soda Machine',
  'Sushi Table',
  'Tea Kettle',
  'Ticket Counterfeiter',
  'Tile Maker',
  'Withergate Anvil',
  'Withergate Furnace',
  'Wizard Crafting Table'
]

export const crops = [
  'Wheat',
  'Corn',
  'Potato',
  'Tomato',
  'Demon Orb',
  'Snappy Plant',
  'Carrot',
  'Shimmeroot',
  'Pepper',
  'Onion',
  'Greenroot',
  'Cinnaberry',
  'Lettuce',
  'Rice',
  'Eggplant',
  'Kraken Kale',
  'Moonplant',
  'Suckerstem',
  'Tombmelon',
  'Razorstalk',
  'Soul Orb',
  'Grapes',
  'Water Fruit',
  'Fire Fruit',
  'Rock Fruit',
  'Wind Chime',
  'Dragon Fruit',
  'Walk Choy',
  'Shiiwalki Mushroom',
  'Indiglow',
  'Acorn',
  'Cat Tail',
  'Mana Gem',
  'Darkness Crop',
  'Guava Berry',
  'Pumpkin',
  'Hops',
  'Soda Pop Crop',
  'Fizzy Fruit',
  'Turnip',
  'Heat Fruit',
  'Marshmallow Bean',
  'Moon Fruit',
  'Butternut',
  'Barley',
  'Yam',
  'Tea Leaves',
  'Ghost Pepper',
  'Kale',
  'Stormelon',
  'Lemon',
  'Armoranth',
  'Chocoberry',
  'Clover',
  'Pineapple',
  'Melon',
  'Heart Berry',
  'Coffee Bean',
  'Garlic',
  'Mango',
  'Durian',
  'Balloon Fruit',
  'Blue Moon Fruit',
  'Hexagon Berry',
  'Star Fruit',
  'Snow Ball Crop',
  'Blizzard Berry',
  'Pythagorean Berry',
  'Cranberry',
  'Kiwi Berry',
  'Green Beans',
  'Peas',
  'Watermelon',
  'Cotton',
  'Honeysuckle',
  'Candy Cane',
  'Snow Pea',
  'Sun Orb',
  'Dead Crop',
  'Honey Flower',
  'Lavender',
  'Hibiscus',
  'Lily',
  'Orchid',
  'Sunflower',
  'Red Rose',
  'Blue Rose',
  'Tulip',
  'Lotus',
  'Daisy',
]

export const trees = [
  'Apple Tree',
  'Blueberry Tree',
  'Candy Corn Fruit Tree',
  'Peach Tree',
  'Raspberry Tree',
  'Strawberry Tree',
  'Fairy Cherry Tree',
  'Gray Scale Tree',
  'Festive Oranges Tree',
  'Monster Fruit Tree',
  'Nectar-ine Tree',
  'Orange Tree',
  'Sour Plum Tree',
  'Sugar Plum Tree'
] 

export const shedSkins = [
  'Basic Shed',
  'TV Shed',
  'Tree Stump Shed',
  'Stein Shed',
  'Pumpkin Shed',
  'Night Club Shed',
  'Mushroom Shed',
  'Ghost Shed',
  'Carnival Shed',
  'Cake Shed',
  'Bee Hive Shed',
  'Elven Stone Shed'
]
